### ISSUE TITLE
assoc-space vs word2vec

### ISSUE THREAD

**Issue by scottlingran** [LuminosoInsight/assoc-space#6]
This library looks great! How does it perform against word2vec?

Is it possible to perform arithmetics in the vector space? e.g. v('king') - v('man') + v('woman') => v('queen')

Also, I'm wondering if anyone's tested this against a word association list? e.g. https://github.com/radialpoint/word2vec-mirror/blob/master/questions-words.txt

**Comment by rspeer** [comment]
This library is outdated now. Sorry that I didn't even see your question until now.

 For something that is a lot more like word2vec (and outperforms it), see:

https://github.com/LuminosoInsight/conceptnet-numberbatch
